from __future__ import annotations

import uuid

import sqlalchemy as sa
from sqlalchemy import (
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from news_pipeline.db.models import Base, GUID, JSONBList


class SimWriter(Base):
    """A competing publisher agent whose style_prompt evolves over time."""

    __tablename__ = "sim_writers"

    id = Column(GUID(), primary_key=True, default=uuid.uuid4)
    name = Column(String(100), unique=True, nullable=False)
    persona_description = Column(Text, nullable=False)
    # Points to the active SimPromptVersion — no FK constraint to avoid circular ref.
    current_version_id = Column(GUID(), nullable=True)
    # Persistent MLflow run_id — one run per writer, accumulates all cycles as steps.
    mlflow_run_id = Column(String(50), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=sa.func.now(), nullable=False)

    prompt_versions = relationship(
        "SimPromptVersion",
        back_populates="writer",
        foreign_keys="SimPromptVersion.writer_id",
        cascade="all, delete-orphan",
        order_by="SimPromptVersion.version_number",
    )
    tweets = relationship("SimTweet", back_populates="writer", cascade="all, delete-orphan")
    cycle_scores = relationship(
        "SimWriterCycleScore", back_populates="writer", cascade="all, delete-orphan"
    )


class SimPromptVersion(Base):
    """One version of a writer's style prompt — the evolutionary lineage."""

    __tablename__ = "sim_prompt_versions"
    __table_args__ = (
        UniqueConstraint("writer_id", "version_number", name="uq_sim_prompt_writer_version"),
    )

    id = Column(GUID(), primary_key=True, default=uuid.uuid4)
    writer_id = Column(
        GUID(), ForeignKey("sim_writers.id", ondelete="CASCADE"), nullable=False
    )
    version_number = Column(Integer, nullable=False)
    style_prompt = Column(Text, nullable=False)
    # Self-referential: which version was mutated to produce this one.
    parent_id = Column(
        GUID(), ForeignKey("sim_prompt_versions.id", ondelete="SET NULL"), nullable=True
    )
    cycle_introduced = Column(Integer, nullable=False, default=0)
    # Engagement score of the *previous* version at the time this mutation was triggered.
    triggered_by_score = Column(Float, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=sa.func.now(), nullable=False)

    writer = relationship(
        "SimWriter", back_populates="prompt_versions", foreign_keys=[writer_id]
    )
    parent = relationship(
        "SimPromptVersion",
        remote_side="SimPromptVersion.id",
        foreign_keys="SimPromptVersion.parent_id",
    )
    tweets = relationship("SimTweet", back_populates="prompt_version")
    cycle_scores = relationship("SimWriterCycleScore", back_populates="prompt_version")


class SimPersona(Base):
    """A reader persona drawn from the 100-persona bank."""

    __tablename__ = "sim_personas"

    id = Column(GUID(), primary_key=True, default=uuid.uuid4)
    name = Column(String(100), unique=True, nullable=False)
    archetype_group = Column(String(50), nullable=False)
    description = Column(Text, nullable=False)

    engagements = relationship(
        "SimEngagement", back_populates="persona", cascade="all, delete-orphan"
    )


class SimCycle(Base):
    """One simulation run — stories in, tweets + engagements out."""

    __tablename__ = "sim_cycles"

    id = Column(GUID(), primary_key=True, default=uuid.uuid4)
    cycle_number = Column(Integer, unique=True, nullable=False)
    week_number = Column(Integer, nullable=False)
    started_at = Column(DateTime(timezone=True), server_default=sa.func.now(), nullable=False)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    story_ids = Column(JSONBList, nullable=False, default=list)
    mlflow_run_id = Column(String(50), nullable=True)

    tweets = relationship("SimTweet", back_populates="cycle", cascade="all, delete-orphan")
    cycle_scores = relationship(
        "SimWriterCycleScore", back_populates="cycle", cascade="all, delete-orphan"
    )


class SimTweet(Base):
    """A tweet generated by one writer about one story in one cycle."""

    __tablename__ = "sim_tweets"
    __table_args__ = (
        Index("ix_sim_tweets_cycle_id", "cycle_id"),
        Index("ix_sim_tweets_writer_id", "writer_id"),
    )

    id = Column(GUID(), primary_key=True, default=uuid.uuid4)
    cycle_id = Column(
        GUID(), ForeignKey("sim_cycles.id", ondelete="CASCADE"), nullable=False
    )
    writer_id = Column(
        GUID(), ForeignKey("sim_writers.id", ondelete="CASCADE"), nullable=False
    )
    prompt_version_id = Column(
        GUID(), ForeignKey("sim_prompt_versions.id", ondelete="SET NULL"), nullable=True
    )
    article_id = Column(
        GUID(), ForeignKey("raw_articles.id", ondelete="SET NULL"), nullable=True
    )
    content = Column(Text, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=sa.func.now(), nullable=False)

    cycle = relationship("SimCycle", back_populates="tweets")
    writer = relationship("SimWriter", back_populates="tweets")
    prompt_version = relationship("SimPromptVersion", back_populates="tweets")
    engagements = relationship(
        "SimEngagement", back_populates="tweet", cascade="all, delete-orphan"
    )


class SimEngagement(Base):
    """One persona's reaction to one tweet."""

    __tablename__ = "sim_engagements"
    __table_args__ = (
        Index("ix_sim_engagements_tweet_id", "tweet_id"),
        Index("ix_sim_engagements_persona_id", "persona_id"),
    )

    id = Column(GUID(), primary_key=True, default=uuid.uuid4)
    tweet_id = Column(
        GUID(), ForeignKey("sim_tweets.id", ondelete="CASCADE"), nullable=False
    )
    persona_id = Column(
        GUID(), ForeignKey("sim_personas.id", ondelete="CASCADE"), nullable=False
    )
    # 'like', 'repost', 'comment', 'skip'
    action = Column(String(20), nullable=False)
    reason = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=sa.func.now(), nullable=False)

    tweet = relationship("SimTweet", back_populates="engagements")
    persona = relationship("SimPersona", back_populates="engagements")


class SimWriterCycleScore(Base):
    """Aggregate engagement score for one writer in one cycle."""

    __tablename__ = "sim_writer_cycle_scores"
    __table_args__ = (
        UniqueConstraint("cycle_id", "writer_id", name="uq_sim_score_cycle_writer"),
        Index("ix_sim_writer_cycle_scores_writer_id", "writer_id"),
    )

    id = Column(GUID(), primary_key=True, default=uuid.uuid4)
    cycle_id = Column(
        GUID(), ForeignKey("sim_cycles.id", ondelete="CASCADE"), nullable=False
    )
    writer_id = Column(
        GUID(), ForeignKey("sim_writers.id", ondelete="CASCADE"), nullable=False
    )
    prompt_version_id = Column(
        GUID(), ForeignKey("sim_prompt_versions.id", ondelete="SET NULL"), nullable=True
    )
    # Normalized 0–1: weighted sum / max possible
    engagement_score = Column(Float, nullable=False, default=0.0)
    repost_count = Column(Integer, nullable=False, default=0)
    like_count = Column(Integer, nullable=False, default=0)
    comment_count = Column(Integer, nullable=False, default=0)
    skip_count = Column(Integer, nullable=False, default=0)
    tweet_count = Column(Integer, nullable=False, default=0)
    reader_sample_count = Column(Integer, nullable=False, default=0)

    cycle = relationship("SimCycle", back_populates="cycle_scores")
    writer = relationship("SimWriter", back_populates="cycle_scores")
    prompt_version = relationship("SimPromptVersion", back_populates="cycle_scores")
